services:
  # Service 1: The Website
  web:
    image: mcd-wrapped:latest
    container_name: mcd-wrapped
    restart: unless-stopped
    command: uvicorn --bind 0.0.0.0:4334 --workers 1 --threads 1 --timeout 60 app:app 
    ports:
      - "4334:4334"
    networks:
      - nginx_default
    environment:
      - PYTHONUNBUFFERED=1

networks:
  nginx_default:
    external: true
